<?php

declare(strict_types=1);

namespace Tests\Performance;

use InvalidArgumentException;
use RuntimeException;

final class SyntheticCsv
{
    /** @return array<string,mixed> */
    public static function create(string $path, string $tag, int $records, int $start = 1, ?int $bytes = null): array
    {
        $header = "date,description,amount,type\n";
        $bytes ??= strlen($header) + $records * 500;
        if ($records < 1 || $start < 1 || $start + $records > 100000000 || preg_match('/\A[a-z-]{1,24}\z/', $tag) !== 1
            || $bytes < strlen($header) + $records * 100 || $bytes > strlen($header) + $records * 1000) {
            throw new InvalidArgumentException('Invalid synthetic CSV shape.');
        }
        $stream = fopen($path, 'xb');
        if ($stream === false) {
            throw new RuntimeException('Cannot create CSV.');
        }
        $width = intdiv($bytes - strlen($header), $records);
        $extra = ($bytes - strlen($header)) % $records;
        $totals = ['records' => $records, 'bytes' => $bytes, 'income_minor' => 0, 'expense_minor' => 0, 'accounts' => []];
        try {
            self::write($stream, $header);
            for ($offset = 0; $offset < $records; $offset++) {
                $serial = $start + $offset;
                $account = 100 + (($serial - 1) % 900);
                $income = $serial % 2 === 0;
                $amount = $income ? 101 : 37;
                $prefix = '2026-08-16,'.$tag.' '.sprintf('%08d', $serial).' ';
                $suffix = ' #'.$account.','.$amount.','.($income ? 'Receita' : 'Despesa')."\n";
                $padding = $width + (int) ($offset < $extra) - strlen($prefix) - strlen($suffix);
                self::write($stream, $prefix.str_repeat('x', $padding).$suffix);
                $totals[$income ? 'income_minor' : 'expense_minor'] += $amount;
                $totals['accounts'][$account] = ($totals['accounts'][$account] ?? 0) + ($income ? $amount : -$amount);
            }
        } finally {
            fclose($stream);
        }
        clearstatcache(true, $path);
        if (filesize($path) !== $bytes) {
            throw new RuntimeException('Incorrect generated byte count.');
        }
        $totals['sha256'] = hash_file('sha256', $path);

        return $totals;
    }

    /** @param resource $stream */
    private static function write($stream, string $bytes): void
    {
        if (fwrite($stream, $bytes) !== strlen($bytes)) {
            throw new RuntimeException('Incomplete CSV write.');
        }
    }
}
